version: '3.7'

services:
  express:
    build: ./express-app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - neo4j-sbx-usw1
      - neo4j-seed-use1
      - neo4j-seed-usw1

  #  neo4j:
  #    image: neo4j:latest
  #    ports:
  #      - "7474:7474"
  #      - "7687:7687"
  #    volumes:
  #      - ./neo4jdata:/data
  #    environment:
  #      - NEO4J_AUTH=none



  neo4j-sbx-usw1:
    image: neo4j:5.22
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./zip-central-neo4j-sbx-usw1/extracted:/data
    environment:
      - NEO4J_AUTH=none


  neo4j-seed-use1:
    image: neo4j:5.22
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./zip-central-neo4j-seed-use1/extracted:/data
    environment:
      - NEO4J_AUTH=none


  neo4j-seed-usw1:
    image: neo4j:5.22
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./zip-central-neo4j-seed-usw1/extracted:/data
    environment:
      - NEO4J_AUTH=none